# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: build
      run: |
        cd master
        npm ci
        npm run build --if-present
        cd ../
    - name: Checkout [release]
      uses: actions/checkout@v2
      with:
        ref: release
        path: release
    - name: commit
      run: |
        cd release
        rm -rf *
        cp ../master/dist/* .
        git config user.email "sabiz@github.com"
        git config user.name "sAbIz"
        git add .
        git commit -m "update"
        git push origin release
