# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        path: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
        run:|
          cd master
          npm ci
          npm run build --if-present
          cd ../
    - name: Checkout [release]
      uses: actions/checkout@v2
      with:
        ref: release
        path: release
    - name: git config
        run:|
          git config --local user.email "sabiz@github.com"
          git config --local user.name "sAbIz"
    - name: commit
      run: |
        cd release
        rm -rf *
        cp ../master/dist/* .
        git add .
        git commit -m "update"
        git push origin release
